services:
  api:
    build: .
    environment:
      YT_API_KEY: $YT_API_KEY
      CLIENT_SECRET: $CLIENT_SECRET
      CLIENT_ID: $CLIENT_ID
      HTTP_SERVER_URL: $HTTP_SERVER_URL
      SAVE_DIR: $SAVE_DIR
      WORKER_COUNT: $WORKER_COUNT
      INVIDIOUS_INSTANCE: $INVIDIOUS_INSTANCE
      PROMETHEUS_MULTIPROC_DIR: $PROMETHEUS_MULTIPROC_DIR
      SENTRY_DSN: $SENTRY_DSN
      ENVIRONMENT: $ENVIRONMENT
      TIMEOUT: $TIMEOUT
      PROXY_URL: $PROXY_URL
      BUILD_SHA: $BUILD_SHA
    ports:
      - $PORT:8000
